name: Publish To Npm

on:
  pull_request:
    branches: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Dependencies
        run: pnpm i
      - name: Build
        run: pnpm -C ./packages/h-ui-plus-components build
#        run: pnpm build --filter h-ui-plus-components
      - name: "Publish to the npm"
        env:
          NPN_AUTH_TOKEN: ${{secrets.NPN_AUTH_TOKEN}}
        run: |
          pnpm config set //registry.npmjs.org/:_authToken "$NPN_AUTH_TOKEN"
          mv ./README.md ./packages/h-ui-plus-components
          pnpm --filter h-ui-plus-components publish --no-git-checks

        # -f 指定子包 ， actions/checkout@v3插件检出的是Head分支，publish发布会提示报错，需要忽略git检查 --no-git-checks
