name: Publish Docs

on:
  pull_request:
    branches: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: "Publish Docs"
        env:
          # 文档仓库 h-ui-plus-docs 的访问token
          GITHUB_TOKEN: ${{secrets.DOCS_GITHUB_TOKEN}}
        run: |
          chmod +x ./sh/publish-docs.sh 
          ./sh/publish-docs.sh 
