name: Publish To Npm

on:
  pull_request:
    branches: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: |
          actions/checkout@v3
          git branch
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Dependencies
        run: pnpm i
      - name: Build
        run: pnpm -C ./packages/h-ui-plus-components build
      - name: "Publish to the npm"
        env:
          NPN_AUTH_TOKEN: ${{secrets.NPN_AUTH_TOKEN}}
        run: |
          pnpm config set registry=https://registry.npmjs.org
          pnpm config set //registry.npmjs.org/:_authToken "$NPN_AUTH_TOKEN"
          pnpm -C ./packages/h-ui-plus-components publish
        
#        该action已停止维护
#        uses: primer/publish@v3 # 用于发布到npm
#        env:
#          # ${{ secrets.xxx }} 是在项目Setting中设置的Actions secrets中设置的秘钥
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # 去npm仓库获取npm的token，并在在Github项目设置中 创建 NPM_AUTH_TOKEN 把获取到的值加进去就行了
#        with:
#          default_branch: "publish" # 默认的发布分支
#          dir: "." #package.json做在目录。默认'.'
